//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAVendors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USAVendors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddProduct {
            get {
                object obj = ResourceManager.GetObject("AddProduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap box_address {
            get {
                object obj = ResourceManager.GetObject("box_address", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross_48 {
            get {
                object obj = ResourceManager.GetObject("cross_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Akrotiri
        ///Albania
        ///Algeria
        ///American Samoa
        ///Andorra
        ///Angola
        ///Anguilla
        ///Antarctica
        ///Antigua and Barbuda
        ///Argentina
        ///Armenia
        ///Aruba
        ///Ashmore and Cartier Islands
        ///Australia
        ///Austria
        ///Azerbaijan
        ///Bahamas, The
        ///Bahrain
        ///Bangladesh
        ///Barbados
        ///Bassas da India
        ///Belarus
        ///Belgium
        ///Belize
        ///Benin
        ///Bermuda
        ///Bhutan
        ///Bolivia
        ///Bosnia and Herzegovina
        ///Botswana
        ///Bouvet Island
        ///Brazil
        ///British Indian Ocean Territory
        ///British Virgin Islands
        ///Brunei
        ///Bulgaria
        ///Burkina Faso
        ///Burma
        ///Burundi
        ///Cambodia
        ///Cameroon
        ///Canad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Drzavi {
            get {
                return ResourceManager.GetString("Drzavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchCode {
            get {
                object obj = ResourceManager.GetObject("searchCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchCompany {
            get {
                object obj = ResourceManager.GetObject("searchCompany", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama
        ///Alaska
        ///Arizona
        ///Arkansas
        ///California
        ///Colorado
        ///Connecticut
        ///Delaware
        ///Florida
        ///Georgia
        ///Hawaii
        ///Idaho
        ///Illinois
        ///Indiana
        ///Iowa
        ///Kansas
        ///Kentucky
        ///Louisiana
        ///Maine
        ///Maryland
        ///Massachusetts
        ///Michigan
        ///Minnesota
        ///Mississippi
        ///Missouri
        ///Montana
        ///Nebraska
        ///Nevada
        ///NewHampshire
        ///NewJersey
        ///NewMexico
        ///NewYork
        ///NorthCarolina
        ///NorthDakota
        ///Ohio
        ///Oklahoma
        ///Oregon
        ///Pennsylvania
        ///RhodeIsland
        ///SouthCarolina
        ///SouthDakota
        ///Tennessee
        ///Texas
        ///Utah
        ///Vermont
        ///Virginia
        ///Washington
        ///WestVirginia
        ///Wisconsin
        ///Wyoming
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vcard {
            get {
                object obj = ResourceManager.GetObject("vcard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
